Repository Manzoomeh/BasisCore.Server.Node, pull requests merged in 2023-12, with the labels that each got.

#42 add and debug api command
  package.json
  renderEngine/Command/RawText.js
  renderEngine/Command/TreeCommand.js
  test/command/CommandUtil.js
  test/command/RawText/simple.js
Labels: bug

#41 adding api command
  .vscode/launch.json
  package.json
  renderEngine/Command/ApiCommand.js
  renderEngine/Command/Source/InlineSourceCommand.js
  test/command/API/runTestApp.js
  test/command/API/simple.js
  test/command/CommandUtil.js
Labels: enhancement

#43 convert type to lowercase
  test/command/CommandUtil.js
Labels: bug, question

#52 Qamsari/34-adding-call-command-to-render-engine
  .vscode/launch.json
  Models/Connection/ConnectionInfo.js
  Models/Connection/ILoadPageResult.js
  Models/Connection/SqlConnectionInfo.js
  Util.js
  package.json
  renderEngine/Command/Collection/CallCommand.js
  renderEngine/Command/Collection/GroupCommand.js
  renderEngine/Command/CommandBase.js
  renderEngine/Command/Source/BaseClasses/SourceCommand.js
  renderEngine/Context/IContext.js
  renderEngine/Context/RequestContext.js
  renderEngine/Models/CallResult.js
  renderEngine/Models/ICommandResult.js
  renderEngine/Token/TokenUtil.js
  test/command/Call/deep.js
  test/command/Call/in-group.js
  test/command/Call/script.sql
  test/command/Call/simple.js
  test/command/CommandUtil.js
  test/command/InlineSource/simple.js
Labels: enhancement

#55 fix issue
  renderEngine/Command/Collection/CallCommand.js
  renderEngine/Models/CallResult.js
Labels: bug

#57 implement inline provider
  .vscode/launch.json
  Models/Connection/ConnectionInfo.js
  Models/Connection/ConnectionUtil.js
  Models/Connection/EdgeConnectionInfo.js
  Models/Connection/InlineConnectionInfo.js
  Models/Connection/SqlConnectionInfo.js
  Models/IRoutingRequest.js
  Models/IWebServer.js
  Models/Index1Response.js
  Models/Index2Response.js
  Models/Index5Response.js
  Models/RequestBaseResponse.js
  Models/request.js
  Services/HttpHostService.js
  Services/hostService.js
  package.json
  test/connection/inline/SoSimple.js
  test/connection/inline/simple.js
  test/connection/sql/simple.js
  test/connection/sql/sql-script.sql
Labels: enhancement
